// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC68dwx5BbO21XwGy-8UDePVAkUCWINpm4',
    appId: '1:836839374831:android:b0982b20a873bc785ac01a',
    messagingSenderId: '836839374831',
    projectId: 'sallah-d2a52',
    databaseURL: 'https://sallah-d2a52-default-rtdb.firebaseio.com',
    storageBucket: 'sallah-d2a52.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-YZkcLnx7FdC-RR-8WJLXvcwPZ92B85I',
    appId: '1:836839374831:ios:43f1afe842b0345e5ac01a',
    messagingSenderId: '836839374831',
    projectId: 'sallah-d2a52',
    databaseURL: 'https://sallah-d2a52-default-rtdb.firebaseio.com',
    storageBucket: 'sallah-d2a52.firebasestorage.app',
    androidClientId: '836839374831-rq800586u9v087mukvfak02t51n1qh0o.apps.googleusercontent.com',
    iosBundleId: 'com.anmka.f',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVHqnvmv2U0-_wV5dW6sCMhLGBC9v9Z-U',
    appId: '1:836839374831:web:1a4b59e222c9a4405ac01a',
    messagingSenderId: '836839374831',
    projectId: 'sallah-d2a52',
    authDomain: 'sallah-d2a52.firebaseapp.com',
    databaseURL: 'https://sallah-d2a52-default-rtdb.firebaseio.com',
    storageBucket: 'sallah-d2a52.firebasestorage.app',
  );

}